### ISSUE TITLE
Info on rebuilding a pg_dump for newer pg versions?

### ISSUE THREAD

**Issue by svrist** [jameshy/pgdump-aws-lambda#1]
Do you have any info on how to rebuild a new pg_dump - for example for pg version 9.6.2 which recently came out.

setting a `-static` in CFLAGS for src/bin/pg_dump in the postgresql source don't seem to generate a useful binary (something about getting homedirectories and password files not possible)

**Comment by readcodelearn** [comment]
@svrist how I did it is
1. spin up amazon ami image on EC2
2. install postgres as normal (default version is 9.5, but you can find packages on the official postgres site for 9.6)
3. scp `/usr/bin/pg_dump` and `/usr/lib64/libpq.so.5.8` as `libpq.so.5`, overwriting the files in `./bin` in the repo

Everything else should still work after

**Comment by jameshy** [comment]
@svrist @readcodelearn

If either of you have time to submit a PR with the latest binaries, I would happily accept!
I want to have the latest stable binaries in this project.

**Comment by readcodelearn** [comment]
@jameshy i can submit a pr with 9.5.8 binary, 9.6 is not officially out in the latest amazon AMI image and it works to dump 9.6 dbs?

**Comment by readcodelearn** [comment]
@jameshy as well there are some other issues such as `moment` and `through2` packages are not in `package.json`, i can roll all of them into one and maybe update the README to include some more instructions on how to load your own versions of the binaries?

**Comment by jameshy** [comment]
@readcodelearn do you mean 9.5.6? An upgrade to 9.5.6 would be good, and of course fix the package.json issue and update the README if you have time!

**Comment by sbv-csis** [comment]
Ah, I thought there was some kind of static linking involved as well...RDS is currently supporting 9.6 - I just took a random 9.6 pg_dump from a debian - it needed quite alot of other shared libs apart from libpq but it ended up working

**Comment by bgaillard** [comment]
Hi, I tried your script today but even with a very small database it is not possible to execute the backup because of the 5 minutes maximum execution time imposed by Amazon Lambda. 

How do you do your backups with this Lambda limitation ?

Anyway here is the procedure to get the binaries I used.

Starts a nano Amazon EC2 machine, login with SSH and enter the following commands to install PostgreSQL 9.6.

```
sudo rpm -i https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-6-x86_64/pgdg-ami201503-96-9.6-2.noarch.rpm`
sudo yum install postgresql96-server postgresql96
```

The files to copy are
* `usr/pgsql-9.6/bin/pg_dump`
* `/usr/pgsql-9.6/lib/libpq.so.5`

If you want to be 100% sure to copy the right `*.so*` files just use the following command to see the dependencies to dynamic libraries.

```
[ec2-user@ip-172-30-0-8 ~]$ ldd /usr/pgsql-9.6/bin/pg_dump
        linux-vdso.so.1 =>  (0x00007fff059dd000)
        libpq.so.5 => /usr/pgsql-9.6/lib/libpq.so.5 (0x00007fb9ead58000)
        libz.so.1 => /lib64/libz.so.1 (0x00007fb9eab3c000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fb9ea77a000)
        libssl.so.10 => /usr/lib64/libssl.so.10 (0x00007fb9ea50d000)
        libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007fb9ea126000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007fb9e9eda000)
        libldap_r-2.4.so.2 => /lib64/libldap_r-2.4.so.2 (0x00007fb9e9c80000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fb9e9a63000)
        /lib64/ld-linux-x86-64.so.2 (0x000055dec24a7000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007fb9e977e000)
        libcom_err.so.2 => /usr/lib64/libcom_err.so.2 (0x00007fb9e957b000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007fb9e9348000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fb9e9144000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007fb9e8f35000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007fb9e8d31000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fb9e8b17000)
        liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007fb9e8908000)
        libsasl2.so.2 => /usr/lib64/libsasl2.so.2 (0x00007fb9e86ec000)
        libssl3.so => /usr/lib64/libssl3.so (0x00007fb9e84a9000)
        libsmime3.so => /usr/lib64/libsmime3.so (0x00007fb9e8282000)
        libnss3.so => /usr/lib64/libnss3.so (0x00007fb9e7f62000)
        libnssutil3.so => /usr/lib64/libnssutil3.so (0x00007fb9e7d36000)
        libplds4.so => /lib64/libplds4.so (0x00007fb9e7b32000)
        libplc4.so => /lib64/libplc4.so (0x00007fb9e792c000)
        libnspr4.so => /lib64/libnspr4.so (0x00007fb9e76ef000)
        libselinux.so.1 => /usr/lib64/libselinux.so.1 (0x00007fb9e74cd000)
        libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007fb9e7296000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fb9e708d000)
        libfreebl3.so => /lib64/libfreebl3.so (0x00007fb9e6e8b000)
```

Please find the files attached to this case, I think we could have an additional `PGVERSION` variable with values `9.5` or `9.6` and create the following structure of files and directories.

```
bin
 | - 9.5
 |     |- pg_dump
 |    |- libpq.so.5
 \ - 9.6
       |- pg_dump
       |- libpq.so.5
```

Hope this helps.

[9.6.zip](https://github.com/jameshy/pgdump-aws-lambda/files/888657/9.6.zip)

**Comment by jameshy** [comment]
@bgaillard Thanks for your notes.

The 5 minute limit didn't affect my usage, because my database is so small.
Perhaps amazon will increase your limit upon request, or maybe in the future they will increase the limit.

**Comment by dfloresgonz** [comment]
how can I update to pg 13?
