### ISSUE TITLE
How to deal with backups that take more than 5 mins?

### ISSUE THREAD

**Issue by sent-hil** [jameshy/pgdump-aws-lambda#10]
Hello!

I'm in need of backing up RDS to S3 and your repo seems like the perfect solution. However I'm not sure the backups will run within 5 mins given the size of the db. Is there a way to specify lambda to run with more resources (not sure about the internals of lambda) so it'll always finish in 5 minutes?

Thanks.

**Comment by jameshy** [comment]
Hello,

If you increase the amount of memory for the lambda function, it will be given more CPU resources, see [Q: How are compute resources assigned to an AWS Lambda function?](https://aws.amazon.com/lambda/faqs/)

Other than that, I don't know how you could guarantee it would finish in 5 minutes.

Hope this helps!
