### ISSUE TITLE
Cannot find Handler

### ISSUE THREAD

**Issue by sebsanchez** [jameshy/pgdump-aws-lambda#21]
Im trying to run this zip using the index.handler as a handler in the lambda function definition but wont find the handler. This is the output i get.

`"errorType": "Runtime.HandlerNotFound",
  "errorMessage": "index.handler is undefined or not exported",
  "trace": [
    "Runtime.HandlerNotFound: index.handler is undefined or not exported",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:144:11)",
    "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:1133:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)",
    "    at Module.load (internal/modules/cjs/loader.js:977:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:877:14)",
    "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)",
    "    at internal/main/run_main_module.js:18:47"
  ]`

And my config

![image](https://user-images.githubusercontent.com/61875191/88194364-08bf9280-cc3f-11ea-8874-6a442378a7d8.png)

**Comment by jameshy** [comment]
Hi @sebsanchez 

I just tested and it works for me 🤷‍♂️ 

Are you sure to be uploading the correct ZIP?

https://github.com/jameshy/pgdump-aws-lambda/releases/download/v1.3.1/pgdump-aws-lambda.zip

**Comment by sebsanchez** [comment]
So i Managed to make it work by unpacking exactly that release and zipping the contents. Seems like there is something wrong with that Zip file. Browsing around i found something about the zip command adding the bash files which might induce the error and thus the zipping must be done using the -r option. 

To recreate you can try to upload that zip from the release as it is, will upload the custom zip i created so we can compare.
[lambda-rds.zip](https://github.com/jameshy/pgdump-aws-lambda/files/4960865/lambda-rds.zip)

**Comment by jameshy** [comment]
But it works for me..
Could you try download it again? maybe your local version is corrupt?

```
>> md5sum pgdump-aws-lambda.zip
3e78238569bedfb321e9767c7e1b4886  pgdump-aws-lambda.zip
```
