### ISSUE TITLE
Feature request - please add support for multiple databases to be backed up, from same PGHOST

### ISSUE THREAD

**Issue by ghost** [jameshy/pgdump-aws-lambda#23]
Hi,

First of all, thanks for your work and sharing this app with the community, it is great!
It would be nice if we could backup multiple databases from the same PGHOST.
Make PGDATABASE accept a CSV list of database names... or * if you wanted to backup all databases on that PGHOST.
Loop through each database in the list, and back them up individually, one after another.
Would that be difficult to implement?

thanks a lot,
Marius

**Comment by jameshy** [comment]
Hi @mariusmanea-fortech,

> Would that be difficult to implement?

Nope, should be quite simple 👍

**Comment by mariusmanea-fortech** [comment]
Awesome! :)
Do you have an idea if/when you can implement that?
I look forward to it..

**Comment by mariusmanea-fortech** [comment]
I would have contributed myself, but my scripting/programming skills are limited to python, bash, some Java and C#.. I've never done JavaScript/nodeJs before. I could probably learn and submit a PR to your repo, but it would take me a lot longer than what it would take you :)

**Comment by sasikumar-cloud** [comment]
Hi,

looks this is great and thanks for sharing the concepts. i received an error while doing the testing actually i changed the region and S3 bucket location then again zip the folder the tested but getting the below error. Can you give me any suggession.

{
  "errorType": "Runtime.HandlerNotFound",
  "errorMessage": "index.handler is undefined or not exported",
  "trace": [
    "Runtime.HandlerNotFound: index.handler is undefined or not exported",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:144:11)",
    "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
    "    at Module.load (internal/modules/cjs/loader.js:950:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:790:14)",
    "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)",
    "    at internal/main/run_main_module.js:17:47"
  ]
}

**Comment by jameshy** [comment]
Support for multiple databases was added in https://github.com/jameshy/pgdump-aws-lambda/pull/65
