### ISSUE TITLE
error dump version 12.4

### ISSUE THREAD

**Issue by razerlock** [jameshy/pgdump-aws-lambda#24]
Hi I wonder, have you ever tried dump using a newer version ( 12.4 ), I tried to update the lib to 12.4 and return with error 

"{"errorType":"Error","errorMessage":"spawn /var/task/bin/postgres-12.4/pg_dump EACCES","code":"EACCES","errno":"EACCES","syscall":"spawn /var/task/bin/postgres-12.4/pg_dump","path":"/var/task/bin/postgres-12.4/pg_dump","spawnargs":["-Fc","-Z1"],"stack":["Error: spawn /var/task/bin/postgres-12.4/pg_dump EACCES","    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)","    at onErrorNT (internal/child_process.js:469:16)","    at processTicksAndRejections (internal/process/task_queues.js:84:21)"]}"

**Comment by james-hutchby-gcx** [comment]
hi @razerlock !
Maybe you need to `chmod +x` the `pg_dump` binary?

**Comment by razerlock** [comment]
Hi @james-hutchby-gcx 
Thank you for a quick responses, I already tried to chmod +x the pg_dump, and it produce the same error.
btw, should I run the "npm run deploy" or can I zip it manually? because when I run "npm run deploy" it always produces error

![image](https://user-images.githubusercontent.com/6947707/98680635-42eea480-2394-11eb-9ef4-ea0a8c090c54.png)

**Comment by razerlock** [comment]
Hi @james-hutchby-gcx 
My bad, after I tried using amazon linux, this works perfectly.
Thanks for script, it help us a lot. 👍
