### ISSUE TITLE
IAM authentication

### ISSUE THREAD

**Issue by nicolasbouton** [jameshy/pgdump-aws-lambda#33]
Hello,
Thanks for your work, it works fine and very helpful !
2 things I would like to bring to your attention:

- support Multiple database backups, but I think this request has already been submitted. I've workarouned this creating one Cloudwatch event per database.
- more information regarding IAM authentication ? I could have the application to connect the RDS using a temporary token but how does the app generates new tokens ?

Thanks a lot and sorry for not contributing more as my skill level in Node.js is close to 0...

Nicolas,

**Comment by tpayne84** [comment]
@nicolasbouton - You could, use this tool to create the temp token -- https://github.com/99designs/aws-vault
