### ISSUE TITLE
Release to npm?

### ISSUE THREAD

**Issue by LeoLapworthKT** [jameshy/pgdump-aws-lambda#51]
Hi,

Thanks for a great project.

Some of the changes we'd like have recently been merged - is it possible for a release to be made to npm?

Many thanks

**Comment by jameshy** [comment]
greetings @LeoLapworthKT!

done :) 

https://www.npmjs.com/package/pgdump-aws-lambda

**Comment by LeoLapworthKT** [comment]
Thank you :)
