### ISSUE TITLE
Bundling pg_restore binary as well as pg_dump?

### ISSUE THREAD

**Issue by bigpresh** [jameshy/pgdump-aws-lambda#53]
Opinion: would you consider bundling `pg_restore` as well as `pg_dump` binaries?  (Maybe starting only for 14+15 to save the effort of going back through each previous version to build them?)

Use case: I'm using `pgdump-aws-lambda` to automate backups of several databases from an Aurora DB cluster - but we want to be able to have a lambda to sync a live DB to a dev/QA DB cluster (for cases where there's an issue that only shows up when dealing with particular data in a live instance)... for that, we need to stream the most recent backup of that DB from S3 into `pg_restore`.

Obviously I can just manually bundle `pg_restore` into the lambda, but for the backup lambda it's nice to be able to just depend on `pgdump-aws-lambda` from npm rather than have to manually bundle stuff - so if `pg_restore` were part of it, that would be most helpful.

#13 asked for this too, and was closed as completed but it seems it didn't happen.

If I were to raise a PR adding `pg_restore` binaries for at least 14.x and 15.x, would you be likely to accept it, or do you think that having `pg_restore` included is out of scope?

**Comment by jameshy** [comment]
@bigpresh In release v1.5.1 i've added `pg_restore` for postgres 14.5 and 15.

**Comment by bigpresh** [comment]
Brilliant!  Many thanks :)

**Comment by Ian-Saura** [comment]
How can i use the pgrestore on the lambda?
Should i modify the handler to take also this module?
