### ISSUE TITLE
Backing up large databases

### ISSUE THREAD

**Issue by muqeet422** [jameshy/pgdump-aws-lambda#61]
The code works perfectly for databases upto 5 GB. However when I tried it with 10GB the resulting object in S3 is unexpectedly small which simply means the it did not worked properly. Also streaming pg_dump seems like using a lot of memory almost as similar to the size of database.

Are there known issues with large databases?

**Comment by jameshy** [comment]
Sorry for the lack of response.

I've tested with a 10.5 GB database and it worked, I could restore the backup from postgres. I didn't see any memory usage problems. Here is the final log output:

```
REPORT RequestId: 82ae1e85-3c9f-4248-81b0-4b60b208582b	Duration: 891830.71 ms	Billed Duration: 891831 ms	Memory Size: 3008 MB	Max Memory Used: 130 MB	
```

You may need to increase the Timeout in the lambda settings, as documented in the [README](https://github.com/jameshy/pgdump-aws-lambda/blob/master/README.md#quick-start).
