### ISSUE TITLE
Request for the addition of the postgresql 16 binary

### ISSUE THREAD

**Issue by barthuygen** [jameshy/pgdump-aws-lambda#68]
Can't figure out how to build the binary for postgresql 16 for lambda, could it be added to the bin folder like all the other versions?

**Comment by jameshy** [comment]
@barthuygen

I've made a [new release](https://github.com/jameshy/pgdump-aws-lambda/releases/tag/v2.0.0) with the 16.3 binaries.

I will close this issue.
