### ISSUE TITLE
SSL Support Issue in v2.0.0

### ISSUE THREAD

**Issue by hxs-sma** [jameshy/pgdump-aws-lambda#71]
After updating from version 1.5.1 to 2.0.0, I encountered an issue with SSL support when RDS requires SSL (setting the parameter `rds.force_ssl` to `1`).

**Error Encountered**:
`pg_dump: error: connection to server at "xxxxx.eu-central-1.rds.amazonaws.com" (10.0.32.99), port 5432 failed: FATAL:  no pg_hba.conf entry for host "10.0.16.79", user "xxxx", database "xxxx", no encryption`

After verifying that there were no network or security group issues, I identified the root cause as the `no encryption` error.

**Attempted Solutions**:

1. **Setting the Environment Variable PGSSLMODE to require**:
`const env = { ...config, LD_LIBRARY_PATH: config.PGDUMP_PATH, PGSSLMODE: 'require' };`
Result: 
This approach failed with the following error, indicating that the pg_dump version used does not support SSL:
`pg_dump: error: sslmode value "require" invalid when SSL support is not compiled in`

2. **Temporary Solution**:
Setting the parameter `rds.force_ssl` to `0` fixed the issue.

**Request**:
- Please provide guidance on how to resolve the issue with SSL support in version 2.0.0.
- If the package does not currently support SSL, please consider adding this functionality or documenting a workaround.

Thank you!

**Comment by jameshy** [comment]
Thanks for the report!

I forgot to enable SSL support when building the 16.3 binaries.

I have built a new release with SSL support: https://github.com/jameshy/pgdump-aws-lambda/releases/tag/v2.0.1.
